### ISSUE TITLE
HomeController Tests

### ISSUE THREAD

**Issue by Yikemlone** [Yikemlone/OurHome#29]
# TODO 
- [x] Add test for for get 200
- [x] Add test for get by ID but 404
- [x] Add test for add but 400 bad request
- [x] Add test for update but 200 response
- [x] Add test for update but 400 bad request
- [x] Add test for delete but 204 response
- [x] Add test for delete but 401 unauthorized
